version: '2'
services:
  nginx:
    build: .
    command: >
      /bin/sh -c
      "envsubst '
      $$NGINX_SERVER_NAME
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    volumes:
      - "./ssl:/etc/nginx/ssl"
      - "./public:/usr/share/nginx/html"
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_SERVER_NAME: "test.example.com"
