version: '2'
services:
  nginx:
    build: .
    container_name: nginx
    command: >
      /bin/sh -c
      "envsubst '
      $$NGINX_SERVER_NAME
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    volumes:
      - "./ssl:/etc/nginx/ssl"
      - "./public:/usr/share/nginx/html"
      - "./log:/var/log/nginx"
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_SERVER_NAME: "test.example.com"
    extra_hosts:
     - local_dev:192.168.0.114
